
[Variables]
GPU0colorFanRpmSelect=255,255,255,50
GPU0colorFanPerSelect=100,250,100,220
GPU0fanMeasureName=HWiNFOGPU0FanPer
GPU0fanUOM=%
GPU0memTotalMeasureName=HWiNFOGPU0MemMaxAMD
;; HWiNFOGPU0MemMax or HWiNFOGPU0MemMaxAMD
GPU0memUsedMeasureName=HWiNFOGPU0MemUsedAMD
;; HWiNFOGPU0Mem or HWiNFOGPU0MemUsedAMD
GPU0colorAMDmemSelect=142,192,124,220
GPU0colorNVmemSelect=255,255,255,50

GPU0SkinLoc=SimplePerfMeters\GPU0
GPU0ConfigSkinLoc=SimplePerfMeters\GPU0\config
GPU0colorFanSelectOFF=255,255,255,50
GPU0fanDisplay=0
